# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b707c63a6ead5c5150965f0db055b969ff7ca06d23ba93669e5357bf912cdc4cb7aed6c59f3354a35f6c9bb527952eef85986df4d52b32ec96feea175579cd67

test:
  secret_key_base: ee97c9191929591c19679765892aed1c917f753d0a9c1088607148a514a81b6b63dd0652578c0bc6275a007e6af47edc361aedf9b23778d527f51bc0278771a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
